### ISSUE TITLE
休眠唤醒重启

### ISSUE THREAD

**Issue by shiruihua1995** [ZqinKing/EFI-HP-ProDesk-600-G1-DM#1]
大佬，使用的时候发现在电脑休眠之后唤醒界面会亮个几秒钟然后就会自动重启不知道啥问题，网上找了一下有人说定制usb端口可以解决，但是定制之后这个问题还是存在，去掉HiDPI也还是有这个问题，不知道大佬有没有遇到过这个问题或者有没有什么解决思路啊

**Comment by ZqinKing** [comment]
我好像没遇到，就是最近升级到了10.15之后hdmi的声音需要拔插一下才行。efi我更新了一些东西，抽空更新上来。
