### ISSUE TITLE
Opencore 注入声卡会卡显卡

### ISSUE THREAD

**Issue by shiruihua1995** [ZqinKing/EFI-HP-ProDesk-600-G1-DM#2]
大佬，请教您一个问题，我自己用OpenCore配置了一个EFI，目前看起来好像没啥问题，但是只要注入alcid跑码的时候就会卡显卡，无论是放在设备属性还是启动参数都不行，我已经尝试了好几天了，也搜索了很多帖，都是还是没有找到解决方案，显卡的platform-id也是和clover中的一致的，不知道大佬有时间能不能帮我看一下，EFI我已经上传github了

![卡显卡的错误图](https://user-images.githubusercontent.com/30557967/94779265-3cfebe80-03f9-11eb-90f3-7af8b37d72d8.jpeg)

**Comment by ZqinKing** [comment]
> 大佬，请教您一个问题，我自己用OpenCore配置了一个EFI，目前看起来好像没啥问题，但是只要注入alcid跑码的时候就会卡显卡，无论是放在设备属性还是启动参数都不行，我已经尝试了好几天了，也搜索了很多帖，都是还是没有找到解决方案，显卡的platform-id也是和clover中的一致的，不知道大佬有时间能不能帮我看一下，EFI我已经上传github了
> 
> ![卡显卡的错误图](https://user-images.githubusercontent.com/30557967/94779265-3cfebe80-03f9-11eb-90f3-7af8b37d72d8.jpeg)

哈哈，不敢称大佬。抽空研究一下。opencore
