### ISSUE TITLE
Cannot connect 2 monitors via DP+DP

### ISSUE THREAD

**Issue by armen181** [ZqinKing/EFI-HP-ProDesk-600-G1-DM#5]

**Comment by armen181** [comment]
as a solution can be use iMac14,4

**Comment by louise13w** [comment]
what is the solution for this?

**Comment by armen181** [comment]
I change iMac15,1 to iMac14,4, the simplest way to do it is to edit the config file with a text editor and replace all iMac15,1 with iMac14,4.
